FROM openjdk:17-alpine

ENV HOST=$HOST
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD

ARG JAR_FILE=app/external-api/build/libs/*.jar

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Duser.timezone=Asia/Seoul", "-jar","/app.jar"]
