# docker image 생성을 위한 dockerfile (설명 -> 아래 링크)
# https://gonii.notion.site/Docker-a01e62e62c1c44abbb7b79e208a6f3cc
FROM openjdk:17-alpine

ENV HOST=$HOST
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD

ARG JAR_FILE=build/libs/*.jar

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Duser.timezone=Asia/Seoul", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005","-jar","/app.jar"]
