spring:
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging.level:
    cos.peerna: ${LOG_LEVEL}
    org:
      springframework:
        security: ${LOG_LEVEL}
